### ISSUE TITLE
No error when social graph is hidden

### ISSUE THREAD

**Issue by Bo-Duke** [Bo-Duke/TootExplorer#1]
When the queried account's social graph is hidden in settings, nothing happens.

It should show a message explaining how to deactivate this (if you want to).

Following count is always in the response so I can just check if we have `followings > 0` while not having a followings list.

**Comment by mabhub** [comment]
Maybe displaying some basic account information could also be a way to show user that operation did something (but didn't give followings)

**Comment by Bo-Duke** [comment]
Closing, two changes live : 

- Basic account information whenever we get it
- Error message when the following list request returns an empty list
